const surevyQuestionsData = [
  {
    question: 'What is your current level of education?',
    key: 'educationLevel',
    isMultiple: false,
    options: [
      'High School Grade 10',
      'High School Grade 11',
      'High School Grade 12',
      'High School Grade 13',
      'Further or Higher Education, Year 1',
      'Further or Higher Education, Year 2',
      'Further or Higher Education, Year 3',
      'Further or Higher Education, Year 4',
      'Post graduate Education',
      'Recent graduate looking for Employment',
    ],
  },
  {
    question:
      'What is the letter grade that best represents your current overall Grade Point Average (GPA)?',
    key: 'gradePoints',
    isMultiple: false,
    options: [
      '(A- to A) GPA of 3.5 or above',
      '(B to B+) GPA of 3.0 to 3.4',
      '(B to B-) GPA of 2.5 to 2.9',
      '(C to B-) GPA of 2.0 to 2.4',
      '(C- to C) GPA of 1.5 to 1.9',
      '(D to C-) GPA of 1.0 to 1.4',
      '(D- to D) GPA of 09 and below',
    ],
  },
  {
    question: 'Where do you consider your next career step to be?',
    key: 'nextCareerStep',
    isMultiple: false,
    options: [
      'Further Education or Technical College',
      'University',
      'Corporate job',
      'Entrepreneurship or Self employment',
      'Apprenticeship or Traineeship',
    ],
  },
  {
    question:
      'Do you have a preference for a geographic location where you would like to study and/or work?',
    key: 'preferredLocation',
    isMultiple: true,
    options: [
      'US',
      'Canada',
      'UK',
      'Europe',
      'Australia',
      'New Zealand',
      'Indian subcontinent',
      'China',
      'Middle East',
      'Far East',
      'Africa',
      'South America',
      'Other',
    ],
  },
  {
    question:
      'What are the top 3 things that you care about most when considering your future education?',
    key: 'top3thingsForFuture',
    isMultiple: true,
    options: [
      'Affordability',
      'Academic ranking and reputation',
      'Academic environment (small class sizes, student/faculty ratio)',
      'Flexibility of delivery (online, classroom, hybrid learning)',
      'Career preparation',
      'Social environment',
      'Physical environment',
    ],
  },
  {
    question: 'What is your current Nationality?',
    key: 'nationality',
    isMultiple: false,
    options: ['India', 'Pakistan', 'America', 'Sri Lanka'],
  },
  {
    question: 'At this point in your career journey, which Career Cluster most appeal to you?',
    key: 'mostAppealCareer',
    isMultiple: false,
    options: [
      'Agriculture, Food & Natural Resources',
      'Architecture & Construction',
      'Arts, Media & Communication',
      'Business Management & Administration',
      'Education & Training',
      'Finance',
      'Government & Public Administration',
      'Health Sciences',
      'Hospitality & Tourism',
      'Community Care & Human Services',
      'Information Technology',
      'Law, Public Safety & Security',
      'Manufacturing',
      'Sales & Marketing',
      'Science, Technology, Engineering & Mathematics',
      'Transportation, Distribution & Logistics',
    ],
  },
  // Add additional questions as needed
];

export default surevyQuestionsData;
